### ISSUE TITLE
3.8.1 Cherry-pick Checklist

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#126]
PRs on `master` that need to be cherry-picked for a 3.8.1:

- [x] https://github.com/sylabs/singularity/pull/162
- [x] https://github.com/sylabs/singularity/pull/153
- [x] https://github.com/sylabs/singularity/pull/151
- [x] https://github.com/sylabs/singularity/pull/150
- [x] https://github.com/sylabs/singularity/pull/128
- [x] https://github.com/sylabs/singularity/pull/121
- [x] https://github.com/sylabs/singularity/pull/111
- [x] https://github.com/sylabs/singularity/pull/98
- [x] https://github.com/sylabs/singularity/pull/97
